# This file is used to get the data which will use in our project from cloud or any github repo

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Sawan-k-yadav/Data-repo/blob/master/cat-dog-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion